server:
  port: 443
  address: 0.0.0.0

lavalink:
  server:
    password: 'mathiscool'
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 4000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ''
  environment: ''

logging:
  file:
    max-history: 5
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO